build.gradle, src/main/java/com/example/oneulnail/common/config/security/JwtTokenProvider.java, src/main/java/com/example/oneulnail/common/config/security/SecurityConfiguration.java, src/main/java/com/example/oneulnail/common/constants/BaseResponseStatus.java, src/main/java/com/example/oneulnail/user/controller/SignController.java, src/main/java/com/example/oneulnail/user/dto/sign/SignInResDto.java, src/main/java/com/example/oneulnail/user/dto/sign/SignUpResDto.java, src/main/java/com/example/oneulnail/user/entity/User.java, src/main/java/com/example/oneulnail/user/repository/UserRepository.java, src/main/java/com/example/oneulnail/user/service/SignService.java, src/main/java/com/example/oneulnail/user/service/UserDetailsServiceImpl.java, src/main/resources/application.yml, src/test/java/com/example/oneulnail/OneulNailApplicationTests.java, src/test/java/com/example/oneulnail/security/SecurityApplicationTests.java
- #3 
- 회원가입 출력 값 수정
- Test코드 작성을 위한 H2 하이버네이트 적용
- 
- 기존 yml코드 수정
- test 코드 작성
- test코드 공부하고 다시 적용할  예정입니다
=> [Fix/#3] JWT 회원가입 출력 값 수정 & TEST코드

src/main/java/com/example/oneulnail/domain/shop/controller/ShopController.java, src/main/java/com/example/oneulnail/domain/shop/dto/request/ShopRegisterReqDto.java, src/main/java/com/example/oneulnail/domain/shop/dto/response/ShopRegisterResDto.java, src/main/java/com/example/oneulnail/domain/shop/entity/Shop.java, src/main/java/com/example/oneulnail/domain/shop/mapper/ShopMapper.java, src/main/java/com/example/oneulnail/domain/shop/repository/ShopRepository.java, src/main/java/com/example/oneulnail/domain/shop/service/ShopService.java, src/main/java/com/example/oneulnail/global/config/security/oauth2/OAuthAttributes.java, src/main/java/com/example/oneulnail/global/config/security/oauth2/controller/OAuth2Controller 2.java, src/main/java/com/example/oneulnail/global/config/security/oauth2/mapper/OAuth2SignUpMapper 2.java, src/main/java/com/example/oneulnail/global/config/security/oauth2/service/CustomOAuth2UserService 2.java, src/main/java/com/example/oneulnail/global/config/security/oauth2/userInfo/KakaoOAuth2UserInfo 2.java
=> feat: Shop 등록 기능 구현

src/main/java/com/example/oneulnail/domain/shop/controller/ShopController.java, src/main/java/com/example/oneulnail/domain/shop/dto/response/ShopFindOneResDto.java, src/main/java/com/example/oneulnail/domain/shop/mapper/ShopMapper.java, src/main/java/com/example/oneulnail/domain/shop/service/ShopService.java
- #19 
- 단일 가게 조회 기능구현
- Test
-
=> feat: 단일 가게 조회 기능구현

src/main/java/com/example/oneulnail/domain/shop/controller/ShopController.java, src/main/java/com/example/oneulnail/domain/shop/dto/response/ShopListResDto.java, src/main/java/com/example/oneulnail/domain/shop/mapper/ShopMapper.java, src/main/java/com/example/oneulnail/domain/shop/repository/ShopRepository.java, src/main/java/com/example/oneulnail/domain/shop/service/ShopService.java
- #22 
- 전체 가게 조회 기능구현
- 페이징 방식으로 구현했습니다.
-
=> feat: 전체 가게 조회 기능구현

src/main/java/com/example/oneulnail/global/config/security/JwtAuthenticationFilter.java, src/main/java/com/example/oneulnail/like_style/controller/LikeStyleController.java, src/main/java/com/example/oneulnail/like_style/dto/request/LikeStyleRegisterReqDto.java, src/main/java/com/example/oneulnail/like_style/dto/request/LikeStyleReqDto.java, src/main/java/com/example/oneulnail/like_style/dto/response/LikeStyleFindResDto.java, src/main/java/com/example/oneulnail/like_style/dto/response/LikeStyleRegisterResDto.java, src/main/java/com/example/oneulnail/like_style/dto/response/LikeStyleResDto.java, src/main/java/com/example/oneulnail/like_style/entity/LikeStyle.java, src/main/java/com/example/oneulnail/like_style/mapper/LikeStyleMapper.java, src/main/java/com/example/oneulnail/like_style/repository/LikeStyleRepository.java, src/main/java/com/example/oneulnail/like_style/service/LikeStyleService.java, src/main/java/com/example/oneulnail/post/entity/Post.java
-  #8 
-  선호 스타일 등록 기능을 구현했습니다. 
- CRUD 기능을 구현했습니다.
-
=> [Feat/#8 ] 선호 스타일 등록 기능 구현 

src/main/java/com/example/oneulnail/domain/post/controller/PostController.java, src/main/java/com/example/oneulnail/domain/post/dto/response/PostFindOneResDto.java, src/main/java/com/example/oneulnail/domain/post/mapper/PostMapper.java, src/main/java/com/example/oneulnail/domain/post/service/PostService.java
=> feat: 게시글 단일 조회

src/main/java/com/example/oneulnail/domain/post/controller/PostController.java, src/main/java/com/example/oneulnail/domain/post/dto/response/PostListResDto.java, src/main/java/com/example/oneulnail/domain/post/mapper/PostMapper.java, src/main/java/com/example/oneulnail/domain/post/repository/PostRepository.java, src/main/java/com/example/oneulnail/domain/post/service/PostService.java, src/main/java/com/example/oneulnail/domain/shop/controller/ShopController.java
=> feat: 게시글 전체 조회

src/main/java/com/example/oneulnail/domain/post/controller/PostController.java, src/main/java/com/example/oneulnail/domain/post/dto/response/PostInfoResDto.java, src/main/java/com/example/oneulnail/domain/post/mapper/PostMapper.java, src/main/java/com/example/oneulnail/domain/post/repository/PostRepository.java, src/main/java/com/example/oneulnail/domain/post/service/PostService.java
=> feat: 카테고리별 게시글 조회

src/main/java/com/example/oneulnail/domain/user/controller/SignController.java, src/main/java/com/example/oneulnail/domain/user/dto/response/SignInResDto.java, src/main/java/com/example/oneulnail/domain/user/dto/response/SignUpResDto.java, src/main/java/com/example/oneulnail/domain/user/mapper/SignMapper.java, src/main/java/com/example/oneulnail/domain/user/service/SignService.java, src/main/java/com/example/oneulnail/global/constants/BaseResponseStatus.java, src/main/java/com/example/oneulnail/global/entity/ExceptionAdvice.java
- #24 
- signMapper 추가함
- 회원가입 폰번호,패스워드,이름 null 값일때 에러처리
- 에러처리 동일한 폰번호, 동일한 이름 추가해야함.
=> [Fix/#24] 자체 로그인/회원가입 구조 정리 & 에러처리

src/main/java/com/example/oneulnail/domain/likePost/controller/LikePostController.java, src/main/java/com/example/oneulnail/domain/likePost/repository/LikePostRepository.java, src/main/java/com/example/oneulnail/domain/likePost/service/LikePostService.java
- #44 
- 유저가 즐겨찾기 해놓은 게시글 조회
- 즐겨찾기 테이블
- 게시글 테이블
- Test
=> feat: 즐겨찾기한 게시글 조회

src/main/java/com/example/oneulnail/domain/likePost/dto/request/LikePostRegisterReqDto.java, src/main/java/com/example/oneulnail/domain/likePost/service/LikePostService.java, src/main/java/com/example/oneulnail/domain/likeStyle/dto/request/LikeStyleRegisterReqDto.java, src/main/java/com/example/oneulnail/domain/likeStyle/dto/request/LikeStyleReqDto.java, src/main/java/com/example/oneulnail/domain/likeStyle/service/LikeStyleService.java, src/main/java/com/example/oneulnail/domain/post/dto/request/PostRegisterReqDto.java, src/main/java/com/example/oneulnail/domain/post/service/PostService.java, src/main/java/com/example/oneulnail/domain/reservation/controller/ReservationController.java, src/main/java/com/example/oneulnail/domain/reservation/dto/response/ReservationInfoResDto.java, src/main/java/com/example/oneulnail/domain/reservation/mapper/ReservationMapper.java, src/main/java/com/example/oneulnail/domain/reservation/repository/ReservationRepository.java, src/main/java/com/example/oneulnail/domain/reservation/service/ReservationService.java, src/main/java/com/example/oneulnail/domain/shop/dto/request/ShopRegisterReqDto.java, src/main/java/com/example/oneulnail/domain/shop/service/ShopService.java, src/main/java/com/example/oneulnail/domain/user/service/SignService.java, src/main/java/com/example/oneulnail/global/config/security/jwt/service/JwtService.java, src/main/java/com/example/oneulnail/global/config/security/oauth2/dto/OAuth2SignUpReqDto.java, src/main/java/com/example/oneulnail/global/config/security/oauth2/service/AuthService.java, src/main/java/com/example/oneulnail/global/config/security/oauth2/service/OAuth2SignUpService.java
- #47 
- 가게 예약 정보 조회 기능구현
- DB에 접근하는 메서드에 `@Transactional` 추가
- JSON 을 RequestDto 객체에 담을 때 기본 생성자가 필요하므로 RequestDto에 `@NoArgsConstructor` 추가
=> Feat/#47 가게 예약 정보 조회

src/main/java/com/example/oneulnail/domain/reservation/controller/ReservationController.java, src/main/java/com/example/oneulnail/domain/reservation/repository/ReservationRepository.java, src/main/java/com/example/oneulnail/domain/reservation/service/ReservationService.java
=> feat: 예약정보 전체 조회

src/main/java/com/example/oneulnail/domain/user/entity/User.java, src/main/java/com/example/oneulnail/global/config/security/jwt/service/JwtService.java, src/main/java/com/example/oneulnail/global/config/security/oauth2/handler/OAuth2LoginSuccessHandler.java
- #51 
- 첫 소셜 로그인 후 추가정보 입력하면 user.role 값이 GUEST -> USER로 바뀐다.
=> Feat/#51 소셜 로그인 추가정보 등록하면 GUEST -> USER로 변경

src/main/java/com/example/oneulnail/domain/cart/entity/Cart.java, src/main/java/com/example/oneulnail/domain/order/entity/Order.java, src/main/java/com/example/oneulnail/domain/product/entity/Product.java
=> Feat/#54 상품,주문, 장바구니 Entity 생성

src/main/java/com/example/oneulnail/domain/cart/entity/Cart.java, src/main/java/com/example/oneulnail/domain/product/entity/Product.java, src/main/java/com/example/oneulnail/domain/reservation/controller/ReservationController.java, src/main/java/com/example/oneulnail/domain/reservation/entity/Reservation.java, src/main/java/com/example/oneulnail/domain/reservation/mapper/ReservationMapper.java, src/main/java/com/example/oneulnail/domain/reservation/service/ReservationService.java
- 장바구니, 상품 엔티티 외래키 변경
- 예약 엔티티에 외래키로 user 추가 후 예약 등록 api 수정
=> hotfix: 외래키 수정 및 예약 등록 수정

Dockerfile, docker-compose.yml, src/main/java/com/example/oneulnail/domain/order/entity/Order.java
- #62 
- Dockerfile 생성
- docker-compose.yml 생성
- RDS 연결하면 mysql 컨테이너 설정은 제거할 예정
=> feat: Docker 설정

src/main/java/com/example/oneulnail/domain/likePost/controller/LikePostController.java, src/main/java/com/example/oneulnail/domain/likePost/service/LikePostService.java, src/main/java/com/example/oneulnail/domain/likeStyle/controller/LikeStyleController.java, src/main/java/com/example/oneulnail/domain/likeStyle/service/LikeStyleService.java, src/main/java/com/example/oneulnail/domain/reservation/controller/ReservationController.java, src/main/java/com/example/oneulnail/domain/reservation/service/ReservationService.java, src/main/java/com/example/oneulnail/global/annotation/LoginUser.java, src/main/java/com/example/oneulnail/global/config/WebConfig.java, src/main/java/com/example/oneulnail/global/config/security/oauth2/controller/OAuth2Controller.java, src/main/java/com/example/oneulnail/global/config/security/oauth2/service/AuthService.java, src/main/java/com/example/oneulnail/global/config/security/oauth2/service/OAuth2SignUpService.java, src/main/java/com/example/oneulnail/global/resolver/LoginUserArgumentResolver.java
- #63 
- resolver 설정
- 각각의 도메인 Controller에 @Login 적용
=> Feat/#63 Resolver 설정 및 @LoginUser 구현

src/main/java/com/example/oneulnail/domain/cart/controller/CartController.java, src/main/java/com/example/oneulnail/domain/cart/dto/request/CartAddReqDto.java, src/main/java/com/example/oneulnail/domain/cart/dto/response/CartInfoResDto.java, src/main/java/com/example/oneulnail/domain/cart/entity/Cart.java, src/main/java/com/example/oneulnail/domain/cart/mapper/CartMapper.java, src/main/java/com/example/oneulnail/domain/cart/repository/CartRepository.java, src/main/java/com/example/oneulnail/domain/cart/service/CartService.java, src/main/java/com/example/oneulnail/global/config/SecurityConfig.java
- #70
- cart 장바구니 생성,조회,삭제
- 장바구니 등록
- 장바구니 조회
- 장바구니 삭제
=> [Feat/#70] cart 장바구니 생성,조회,삭제

docker-compose.yml, src/main/java/com/example/oneulnail/domain/user/service/SignService.java
- #68 
- 유효성 검증을 지나고 있어서 refresh를 찾지 못하고 있던거 수정
=> [Fix/#68] refresh토큰 유효검증 수정

build.gradle, src/main/java/com/example/oneulnail/domain/post/controller/PostController.java, src/main/java/com/example/oneulnail/domain/post/service/PostService.java, src/main/java/com/example/oneulnail/domain/product/controller/ProductCotroller.java, src/main/java/com/example/oneulnail/domain/product/service/ProductService.java, src/main/java/com/example/oneulnail/domain/shop/controller/ShopController.java, src/main/java/com/example/oneulnail/domain/shop/service/ShopService.java, src/main/java/com/example/oneulnail/global/config/S3Config.java, src/main/java/com/example/oneulnail/global/constants/S3Upload.java
- #74 
- was s3 추가
- s3 config
- s3upload 이용해서 이미지 저장
=> [Feat/#74] AWS S3 설정

src/main/java/com/example/oneulnail/domain/post/controller/PostController.java, src/main/java/com/example/oneulnail/domain/product/controller/ProductCotroller.java, src/main/java/com/example/oneulnail/domain/shop/controller/ShopController.java, src/main/java/com/example/oneulnail/domain/shop/service/ShopService.java
=> [Feat/#75]  에러 수정
